using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Omnia.Pie.Vtm.Devices.Interface
{
	public enum EmvTag
	{
		_9F01 = 0,		//  Acquirer Identifier
		_9F40 = 1,		//  Additional Terminal Capability
		_81 = 2,		//  Amount Authorized (Binary)
		_9F02 = 3,		//  Amount Authorized (Numeric)
		_9F04 = 4,		//  Amount Other (Binary)
		_9F03 = 5,		//  Amount Other (Numeric)
		_9F3A = 6,		//  Amount Reference Currency
		_DF01 = 7,		//  Amount Transaction
		_9F26 = 8,		//  Application Cryptogram
		_9F42 = 9,		//  Application Currency Code
		_9F44 = 10,		//  Application Currency Exponent
		_9F05 = 11,		//   Application Discretionary Data
		_5F25 = 12,		//  Application Effective Date
		_5F24 = 13,		//  Application Expired Date
		_94 = 14,		//  Application File Locator
		_4F = 15,		//  Application Identifier
		_82 = 16,		//  Application Interchange Profile
		_50 = 17,		//  Application Label
		_9F12 = 18,     //  Application Preferred Name
		_5A = 19,     //  Primary Account Number
		_5F34 = 20,     //  Primary Account Sequence Number
		_87 = 21,     //  Application Priority Indicator
		_9F3B = 22,     //  Application Reference Currency
		_9F43 = 23,     //  Application Reference Currency Exponent
		_9F36 = 24,     //  Application Transaction Counter
		_9F07 = 25,     //  Application Usage Control
		_9F08 = 26,     //  ICC Application Version Number
		_9F09 = 27,     //  Terminal Application Version Number
		_8A = 28,     //  Authorization Response Code
		_8C = 29,     //  CDOL1
		_8D = 30,     //  CDOL2
		_5F20 = 31,     //  Cardholder Name
		_9F0B = 32,     //  Cardholder Name Extended
		_8E = 33,     //  Cardholder Verification Method List
		_9F34 = 34,     //  Cardholder Verification Method Result
		_8F = 35,     //  CA Public Key Index
		_9F27 = 36,     //  Cryptogram Information Data
		_9F45 = 37,     //  Data Authorization Code
		_84 = 38,     //  DF Name
		_D6 = 39,     //  Default DDOL
		_D7 = 40,     //  Default TDOL
		_DF02 = 41,     //  Enciphered PIN Data
		_9F49 = 42,     //  DDOL
		_BF0C = 43,     //  FCI Issuer Discretionary Data
		_9F4C = 44,     //  ICC Dynamic Data
		_9F2D = 45,     //  ICC PIN Public Key Certificate
		_9F2E = 46,     //  ICC PIN Public Key Exponent
		_9F2F = 47,     //  ICC PIN Public Key Remainder
		_9F46 = 48,     //  ICC Public Key Certificate
		_9F47 = 49,     //  ICC Public Key Exponent
		_9F48 = 50,     //  ICC Public Key Remainder
		_9F1E = 51,     //  IFD Serial Number
		_9F0D = 52,     //  Issuer Action Code Default
		_9F0E = 53,     //  Issuer Action Code Denial
		_9F0F = 54,     //  Issuer Action Code Online
		_9F10 = 55,     //  Issuer Application Date
		_91 = 56,     //  Issuer Authorization Data
		_9F11 = 57,     //  Issuer Code Table Index
		_5F28 = 58,     //  Issuer Country Code
		_90 = 59,     //  Issuer Public Key Certificate
		_9F32 = 60,     //  Issuer Public Key Exponent
		_92 = 61,     //  Issuer Public Key Remainder
		_9F18 = 62,     //  Issuer Script Identifier
		_DF03 = 63,     //  Issuer Script Result
		_71 = 64,     //  Issuer Script Template 1
		_72 = 65,     //  Issuer Script Template 2
		_5F2D = 66,     //  Language Preference
		_9F13 = 67,     //  Last Online Application Transaction Counter
		_9F14 = 68,     //  Lower Offline Limit
		_9F15 = 69,     //  Merchant Category Code
		_9F16 = 70,     //  Merchant Identifier
		_DF04 = 71,     //  Merchant Name Location
		_DF05 = 72,     //  Message Type
		_9F39 = 73,     //  POS Entry Code
		_9F38 = 74,     //  PDOL
		_5F30 = 75,     //  Service Code
		_9F4B = 76,     //  Signed Dynamic Application Data
		_93 = 77,     //  Signed Static Application Data
		_9F4A = 78,     //  Static Data Authentication Tag List
		_D8 = 79,     //  Terminal Action Code Default
		_D9 = 80,     //  Terminal Action Code Denial
		_DA = 81,     //  Terminal Action Code Online
		_9F33 = 82,     //  Terminal Capability
		_9F1A = 83,     //  Terminal Country Code
		_9F1B = 84,     //  Terminal Floor Limit
		_9F1C = 85,     //  Terminal Identifier
		_9F1D = 86,     //  Terminal Risk Management Data
		_9F35 = 87,     //  Terminal Type
		_95 = 88,     //  Terminal Verification Result
		_9F1F = 89,     //  Track1 Discretionary Data
		_9F20 = 90,     //  Track2 Discretionary Data
		_57 = 91,     //  Track2 Equivalent Data
		_97 = 92,     //  TDOL
		_98 = 93,     //  Transaction Certificate Hash Value
		_5F2A = 94,     //  Transaction Currency Code
		_5F36 = 95,     //  Transaction Currency Exponent
		_9A = 96,     //  Transaction Date
		_9F3C = 97,     //  Transaction Reference Currency Code
		_DB = 98,     //  Transaction Reference Currency Conversion
		_9F3D = 99,     //  Transaction Reference Currency Exponent
		_9F41 = 100,     //  Transaction Sequence Counter
		_9B = 101,     //  Transaction Status Information
		_9F21 = 102,     //  Transaction Time
		_9C = 103,     //  Transaction Type
		_9F37 = 104,     //  Unpredictable Number
		_9F23 = 105,     //  Upper Offline Limit
		_D1 = 106,     //  Installment Number
		_D4 = 107,     //  Approval Number
		_DF06 = 108,     //  Issuer Public Key
		_DF07 = 109,     //  Static Application Data
		_D2 = 110,     //  Tax Amount
		_D3 = 111,     //  Service Fee
		_D5 = 112,     //  Original Transaction Date
		_DC = 113,     //  Merchant No
		_DE = 114,     //  Original Approval No
		_DF08 = 115,     //  Acquirer Name
		_DF09 = 116,     //  Host Message
		_DF0A = 117,     //  Terminal Counter
		_DF0B = 118,     //  Recovered ICC Public Key
		_DF0C = 119,     //  Dynamic Application Data
		_9F06 = 120,     //  Application Identifier (AID) - terminal
		_9F22 = 121,     //  Certification Authority Public Key Index
		_DF0D = 122,     //  Target Percentage
		_DF0E = 123,     //  Threshold Value
		_DF0F = 124,     //  Maximum Target Percentage
		_9F53 = 125,     //  Transaction Category Code
		_DF1D = 126,     //  Host Notice
		_DF1E = 127,     //  Display Control
		_9F4D = 128,     //  Log Entry
		_5F57 = 129     //  Account Type
	}
}