//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.Pie.Vtm.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Omnia.Pie.Vtm.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AADC BILL PAYMENT.
        /// </summary>
        public static string AadcAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("AadcAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AADC BILL PAYMENT.
        /// </summary>
        public static string AadcCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("AadcCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT NO:.
        /// </summary>
        public static string AccountNumberColon {
            get {
                return ResourceManager.GetString("AccountNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDC BILL PAYMENT.
        /// </summary>
        public static string AddcAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("AddcAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CASH.
        /// </summary>
        public static string AddCashReceipt {
            get {
                return ResourceManager.GetString("AddCashReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDC BILL PAYMENT.
        /// </summary>
        public static string AddcCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("AddcCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT TOTAL:.
        /// </summary>
        public static string AmountTotalColon {
            get {
                return ResourceManager.GetString("AmountTotalColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION ID:.
        /// </summary>
        public static string ApplicationIdColon {
            get {
                return ResourceManager.GetString("ApplicationIdColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION LABEL:.
        /// </summary>
        public static string ApplicationLabelColon {
            get {
                return ResourceManager.GetString("ApplicationLabelColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH CODE:.
        /// </summary>
        public static string AuthCodeColon {
            get {
                return ResourceManager.GetString("AuthCodeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE BALANCE:.
        /// </summary>
        public static string AvailableBalanceColon {
            get {
                return ResourceManager.GetString("AvailableBalanceColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE INQUIRY.
        /// </summary>
        public static string BalanceInquiryReceipt {
            get {
                return ResourceManager.GetString("BalanceInquiryReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card is blocked..
        /// </summary>
        public static string BlockedCardExceptionMessage {
            get {
                return ResourceManager.GetString("BlockedCardExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your card has been captured.
        /// </summary>
        public static string CardCaptured {
            get {
                return ResourceManager.GetString("CardCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card should be captured..
        /// </summary>
        public static string CardCaptureExceptionMessage {
            get {
                return ResourceManager.GetString("CardCaptureExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARDLESS WITHDRAWAL.
        /// </summary>
        public static string CardlessCashWithdrawalReceipt {
            get {
                return ResourceManager.GetString("CardlessCashWithdrawalReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARD NO:.
        /// </summary>
        public static string CardNumberColon {
            get {
                return ResourceManager.GetString("CardNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH DEPOSIT.
        /// </summary>
        public static string CashDepositToAccountReceipt {
            get {
                return ResourceManager.GetString("CashDepositToAccountReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT CARD PAYMENT.
        /// </summary>
        public static string CashDepositToCreditCardReceipt {
            get {
                return ResourceManager.GetString("CashDepositToCreditCardReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ BNA COUNT INFO ].
        /// </summary>
        public static string CashInReceipt {
            get {
                return ResourceManager.GetString("CashInReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH WITHDRAWAL.
        /// </summary>
        public static string CashWithdrawalUsingCreditCardReceipt {
            get {
                return ResourceManager.GetString("CashWithdrawalUsingCreditCardReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH WITHDRAWAL.
        /// </summary>
        public static string CashWithdrawalUsingDebitCardReceipt {
            get {
                return ResourceManager.GetString("CashWithdrawalUsingDebitCardReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH WITHDRAWAL.
        /// </summary>
        public static string CashWithdrawalUsingOffusCardReceipt {
            get {
                return ResourceManager.GetString("CashWithdrawalUsingOffusCardReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque book pending..
        /// </summary>
        public static string ChequeBookPendingExceptionMessage {
            get {
                return ResourceManager.GetString("ChequeBookPendingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEQUE BOOK REQUEST.
        /// </summary>
        public static string ChequeBookRequestReceipt {
            get {
                return ResourceManager.GetString("ChequeBookRequestReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque book will be delivered through courier after 2 working days subject to your eligibility.
        /// </summary>
        public static string ChequeBookRequestSuccess {
            get {
                return ResourceManager.GetString("ChequeBookRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cheque deposit has been accepted and will be processed within 4 working days subject to verification.
        /// </summary>
        public static string ChequeDepositSuccessMessage {
            get {
                return ResourceManager.GetString("ChequeDepositSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChequeDepositToAccountReceiptFooter {
            get {
                return ResourceManager.GetString("ChequeDepositToAccountReceiptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEQUE DEPOSIT.
        /// </summary>
        public static string ChequeDepositToAccountReceiptHeader {
            get {
                return ResourceManager.GetString("ChequeDepositToAccountReceiptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChequeDepositToCreditCardReceiptFooter {
            get {
                return ResourceManager.GetString("ChequeDepositToCreditCardReceiptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEQUE DEPOSIT.
        /// </summary>
        public static string ChequeDepositToCreditCardReceiptHeader {
            get {
                return ResourceManager.GetString("ChequeDepositToCreditCardReceiptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Leaves Issuance.
        /// </summary>
        public static string ChequePrinting {
            get {
                return ResourceManager.GetString("ChequePrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR ADD CASH.
        /// </summary>
        public static string ClearAddCashReceipt {
            get {
                return ResourceManager.GetString("ClearAddCashReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR CARDS.
        /// </summary>
        public static string ClearCardsReceipt {
            get {
                return ResourceManager.GetString("ClearCardsReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR CASH DEPOSIT.
        /// </summary>
        public static string ClearCashInReceipt {
            get {
                return ResourceManager.GetString("ClearCashInReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR CHEQUES.
        /// </summary>
        public static string ClearChequesReceipt {
            get {
                return ResourceManager.GetString("ClearChequesReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSUMER NO:.
        /// </summary>
        public static string ConsumerNumberColon {
            get {
                return ResourceManager.GetString("ConsumerNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be contacted within 2 business days.
        /// </summary>
        public static string ContactedMessage {
            get {
                return ResourceManager.GetString("ContactedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT CARD BALANCE.
        /// </summary>
        public static string CreditCardBalanceReceipt {
            get {
                return ResourceManager.GetString("CreditCardBalanceReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT CARD NO:.
        /// </summary>
        public static string CreditCardNumberColon {
            get {
                return ResourceManager.GetString("CreditCardNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT CARD PAYMENT.
        /// </summary>
        public static string CreditCardPaymentReceipt {
            get {
                return ResourceManager.GetString("CreditCardPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDIT LIMIT:.
        /// </summary>
        public static string CreditLimitColon {
            get {
                return ResourceManager.GetString("CreditLimitColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENOMINATION.
        /// </summary>
        public static string Denomination {
            get {
                return ResourceManager.GetString("Denomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT ACCOUNT:.
        /// </summary>
        public static string DepositAccountNumberColon {
            get {
                return ResourceManager.GetString("DepositAccountNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT AMOUNT:.
        /// </summary>
        public static string DepositAmountColon {
            get {
                return ResourceManager.GetString("DepositAmountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit By:.
        /// </summary>
        public static string DepositByColon {
            get {
                return ResourceManager.GetString("DepositByColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT COUNT.
        /// </summary>
        public static string DepositCount {
            get {
                return ResourceManager.GetString("DepositCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEWA BILL PAYMENT.
        /// </summary>
        public static string DewaAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("DewaAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEWA BILL PAYMENT.
        /// </summary>
        public static string DewaCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("DewaCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees displayed are inclusive of VAT amount.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary ID already exists..
        /// </summary>
        public static string DuplicateBeneficiaryExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateBeneficiaryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead already exists..
        /// </summary>
        public static string DuplicateLeadExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateLeadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DU POSTPAID.
        /// </summary>
        public static string DuPostpaidAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("DuPostpaidAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DU POSTPAID.
        /// </summary>
        public static string DuPostpaidCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("DuPostpaidCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DU PREPAID.
        /// </summary>
        public static string DuPrepaidAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("DuPrepaidAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DU PREPAID.
        /// </summary>
        public static string DuPrepaidCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("DuPrepaidCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailColon {
            get {
                return ResourceManager.GetString("EmailColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already registered. .
        /// </summary>
        public static string EmailExistExceptionMessage {
            get {
                return ResourceManager.GetString("EmailExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EID AUTHENTICATION.
        /// </summary>
        public static string EmiratesIdAuthentication {
            get {
                return ResourceManager.GetString("EmiratesIdAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETISALAT E-LIFE.
        /// </summary>
        public static string EtisalatElifeAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("EtisalatElifeAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETISALAT E-LIFE.
        /// </summary>
        public static string EtisalatElifeCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("EtisalatElifeCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETISALAT POSTPAID.
        /// </summary>
        public static string EtisalatPostpaidAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("EtisalatPostpaidAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETISALAT POSTPAID.
        /// </summary>
        public static string EtisalatPostpaidCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("EtisalatPostpaidCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETISALAT WASEL.
        /// </summary>
        public static string EtisalatWaselAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("EtisalatWaselAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETISALAT WASEL.
        /// </summary>
        public static string EtisalatWaselCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("EtisalatWaselCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of OTP count exceeded..
        /// </summary>
        public static string ExceededOtpExceptionMessage {
            get {
                return ResourceManager.GetString("ExceededOtpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of PIN count exceeded..
        /// </summary>
        public static string ExceededPinExceptionMessage {
            get {
                return ResourceManager.GetString("ExceededPinExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer has exceeded his withdrawal limit..
        /// </summary>
        public static string ExceededWithdrawalLimitExceptionMessage {
            get {
                return ResourceManager.GetString("ExceededWithdrawalLimitExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card is expired..
        /// </summary>
        public static string ExpiredCardExceptionMessage {
            get {
                return ResourceManager.GetString("ExpiredCardExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN Printing.
        /// </summary>
        public static string IBANPrinting {
            get {
                return ResourceManager.GetString("IBANPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance in the account..
        /// </summary>
        public static string InsufficientAccountBalanceExceptionMessage {
            get {
                return ResourceManager.GetString("InsufficientAccountBalanceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer has exceeded his credit limit..
        /// </summary>
        public static string InsufficientCreditCardBalanceExceptionMessage {
            get {
                return ResourceManager.GetString("InsufficientCreditCardBalanceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS AN INTERIM BALANCE ONLY SUBJECT TO CONFIRMATION.
        /// </summary>
        public static string InterimBalanceDisclaimer {
            get {
                return ResourceManager.GetString("InterimBalanceDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is invalid..
        /// </summary>
        public static string InvalidAccountExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidAccountExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card is invalid..
        /// </summary>
        public static string InvalidCreditCardExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidCreditCardExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer is invalid..
        /// </summary>
        public static string InvalidCustomerExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidCustomerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Emirates ID.
        /// </summary>
        public static string InvalidEmiratesIDExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidEmiratesIDExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect..
        /// </summary>
        public static string InvalidLoginExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidLoginExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is invalid..
        /// </summary>
        public static string InvalidOtpExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidOtpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is invalid..
        /// </summary>
        public static string InvalidPinExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidPinExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is invalid..
        /// </summary>
        public static string InvalidTransactionExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidTransactionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Certificate request.
        /// </summary>
        public static string LiabilityCertificateRequest {
            get {
                return ResourceManager.GetString("LiabilityCertificateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIA TYPE:.
        /// </summary>
        public static string MediaTypeColon {
            get {
                return ResourceManager.GetString("MediaTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICR:.
        /// </summary>
        public static string MicrColon {
            get {
                return ResourceManager.GetString("MicrColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINI STATEMENT.
        /// </summary>
        public static string MinistatementReceipt {
            get {
                return ResourceManager.GetString("MinistatementReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile:.
        /// </summary>
        public static string MobileColon {
            get {
                return ResourceManager.GetString("MobileColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mobile number is already registered..
        /// </summary>
        public static string MobileExistExceptionMessage {
            get {
                return ResourceManager.GetString("MobileExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOBILE NO:.
        /// </summary>
        public static string MobileNumberColon {
            get {
                return ResourceManager.GetString("MobileNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months Requested.
        /// </summary>
        public static string MonthsRequested {
            get {
                return ResourceManager.GetString("MonthsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Liability Certificate request.
        /// </summary>
        public static string NonLiabilityCertificateRequest {
            get {
                return ResourceManager.GetString("NonLiabilityCertificateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RECORDS.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions available.
        /// </summary>
        public static string NoTransactionsAvailable {
            get {
                return ResourceManager.GetString("NoTransactionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of leaves requested.
        /// </summary>
        public static string NumberOfLeaves {
            get {
                return ResourceManager.GetString("NumberOfLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE INQUIRY.
        /// </summary>
        public static string OffusCardBalanceReceipt {
            get {
                return ResourceManager.GetString("OffusCardBalanceReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect..
        /// </summary>
        public static string OutOfServiceExceptionMessage {
            get {
                return ResourceManager.GetString("OutOfServiceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTSTANDING AMOUNT:.
        /// </summary>
        public static string OutstandingAmountColon {
            get {
                return ResourceManager.GetString("OutstandingAmountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password. Please try again later..
        /// </summary>
        public static string PasswordFailExceptionMessage {
            get {
                return ResourceManager.GetString("PasswordFailExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT AMOUNT:.
        /// </summary>
        public static string PaymentAmountColon {
            get {
                return ResourceManager.GetString("PaymentAmountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Users.
        /// </summary>
        public static string PrintUsersReceipt {
            get {
                return ResourceManager.GetString("PrintUsersReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECHARGE:.
        /// </summary>
        public static string RechargeAmountColon {
            get {
                return ResourceManager.GetString("RechargeAmountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number:.
        /// </summary>
        public static string ReferenceNumberColon {
            get {
                return ResourceManager.GetString("ReferenceNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint registered successfully..
        /// </summary>
        public static string RegisterFingerprintReceipt {
            get {
                return ResourceManager.GetString("RegisterFingerprintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string RepositoryExceptionMessage {
            get {
                return ResourceManager.GetString("RepositoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIK BILL PAYMENT.
        /// </summary>
        public static string SalikAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("SalikAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIK BILL PAYMENT.
        /// </summary>
        public static string SalikCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("SalikCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEWA BILL PAYMENT.
        /// </summary>
        public static string SewaAccountBillPaymentReceipt {
            get {
                return ResourceManager.GetString("SewaAccountBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEWA BILL PAYMENT.
        /// </summary>
        public static string SewaCreditCardBillPaymentReceipt {
            get {
                return ResourceManager.GetString("SewaCreditCardBillPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM ACCOUNT:.
        /// </summary>
        public static string SourceAccountColon {
            get {
                return ResourceManager.GetString("SourceAccountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Printing.
        /// </summary>
        public static string StatementPrintDeductionReceipt {
            get {
                return ResourceManager.GetString("StatementPrintDeductionReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Printing.
        /// </summary>
        public static string StatementPrinting {
            get {
                return ResourceManager.GetString("StatementPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO ACCOUNT:.
        /// </summary>
        public static string TargetAccountColon {
            get {
                return ResourceManager.GetString("TargetAccountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVICE ID.
        /// </summary>
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST CASH.
        /// </summary>
        public static string TestCashReceipt {
            get {
                return ResourceManager.GetString("TestCashReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANK YOU FOR USING AL RAJHI DIGITAL BANKING SERVICES.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANK YOU FOR USING UAE SWITCH ATM.
        /// </summary>
        public static string ThankYouUAESwitch {
            get {
                return ResourceManager.GetString("ThankYouUAESwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection has timed out..
        /// </summary>
        public static string TimeoutExceptionMessage {
            get {
                return ResourceManager.GetString("TimeoutExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fees.
        /// </summary>
        public static string TotalFees {
            get {
                return ResourceManager.GetString("TotalFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER AMOUNT:.
        /// </summary>
        public static string TransactionAmountColon {
            get {
                return ResourceManager.GetString("TransactionAmountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date:.
        /// </summary>
        public static string TransactionDateColon {
            get {
                return ResourceManager.GetString("TransactionDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction declined.
        /// </summary>
        public static string TransactionDeclined {
            get {
                return ResourceManager.GetString("TransactionDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the transaction. Hardware Failure.
        /// </summary>
        public static string TransactionDeclinedHardwareError {
            get {
                return ResourceManager.GetString("TransactionDeclinedHardwareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSN:.
        /// </summary>
        public static string TransactionNumberColon {
            get {
                return ResourceManager.GetString("TransactionNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESSFULL TRANSACTION.
        /// </summary>
        public static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUND TRANSFER.
        /// </summary>
        public static string TransferFundsReceipt {
            get {
                return ResourceManager.GetString("TransferFundsReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CUSTOMER DETAILS.
        /// </summary>
        public static string UpdateCustomerDetailsAddressReceipt {
            get {
                return ResourceManager.GetString("UpdateCustomerDetailsAddressReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CUSTOMER DETAILS.
        /// </summary>
        public static string UpdateCustomerDetailsEmailReceipt {
            get {
                return ResourceManager.GetString("UpdateCustomerDetailsEmailReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CUSTOMER DETAILS.
        /// </summary>
        public static string UpdateCustomerDetailsEmiratesIdReceipt {
            get {
                return ResourceManager.GetString("UpdateCustomerDetailsEmiratesIdReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CUSTOMER DETAILS.
        /// </summary>
        public static string UpdateCustomerDetailsMobileReceipt {
            get {
                return ResourceManager.GetString("UpdateCustomerDetailsMobileReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Customer Details have been updated successfully..
        /// </summary>
        public static string UpdateCustomerDetailsSuccess {
            get {
                return ResourceManager.GetString("UpdateCustomerDetailsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED ADDRESS:.
        /// </summary>
        public static string UpdatedAddressColon {
            get {
                return ResourceManager.GetString("UpdatedAddressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED EMAIL:.
        /// </summary>
        public static string UpdatedEmailColon {
            get {
                return ResourceManager.GetString("UpdatedEmailColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED EXPIRY DATE:.
        /// </summary>
        public static string UpdatedEmiratesIdExpiryDateColon {
            get {
                return ResourceManager.GetString("UpdatedEmiratesIdExpiryDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED EID NO:.
        /// </summary>
        public static string UpdatedEmiratesIdNumberColon {
            get {
                return ResourceManager.GetString("UpdatedEmiratesIdNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED MOBILE NO:.
        /// </summary>
        public static string UpdatedMobileNumberColon {
            get {
                return ResourceManager.GetString("UpdatedMobileNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update information. Please try again later..
        /// </summary>
        public static string UpdateInfoExceptionMessage {
            get {
                return ResourceManager.GetString("UpdateInfoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Updated Successfully.
        /// </summary>
        public static string UpdateInfoReceipt {
            get {
                return ResourceManager.GetString("UpdateInfoReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the user. Please try again later..
        /// </summary>
        public static string UserCreateExcetionMessage {
            get {
                return ResourceManager.GetString("UserCreateExcetionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string UsernameColon {
            get {
                return ResourceManager.GetString("UsernameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already registered..
        /// </summary>
        public static string UsernameExistExceptionMessage {
            get {
                return ResourceManager.GetString("UsernameExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ADD CASH.
        /// </summary>
        public static string ViewAddCashReceipt {
            get {
                return ResourceManager.GetString("ViewAddCashReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITHDRAWAL AMOUNT:.
        /// </summary>
        public static string WithdrawalAmountColon {
            get {
                return ResourceManager.GetString("WithdrawalAmountColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request Ref Number Is.
        /// </summary>
        public static string YourRequestRefnumberis {
            get {
                return ResourceManager.GetString("YourRequestRefnumberis", resourceCulture);
            }
        }
    }
}
