//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnia.Pie.Vtm.Workflow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Omnia.Pie.Vtm.Workflow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Selection.
        /// </summary>
        public static string StepAccountSelection {
            get {
                return ResourceManager.GetString("StepAccountSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount and Date.
        /// </summary>
        public static string StepAmountAndDate {
            get {
                return ResourceManager.GetString("StepAmountAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Selection.
        /// </summary>
        public static string StepCardSelection {
            get {
                return ResourceManager.GetString("StepCardSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Confirmation.
        /// </summary>
        public static string StepChargesConfirmation {
            get {
                return ResourceManager.GetString("StepChargesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string StepConfirmation {
            get {
                return ResourceManager.GetString("StepConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Details.
        /// </summary>
        public static string StepCreditCardDetails {
            get {
                return ResourceManager.GetString("StepCreditCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denomination.
        /// </summary>
        public static string StepDenomination {
            get {
                return ResourceManager.GetString("StepDenomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispense Cash.
        /// </summary>
        public static string StepDispenseCash {
            get {
                return ResourceManager.GetString("StepDispenseCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encash Confirmation.
        /// </summary>
        public static string StepEncashConfirmation {
            get {
                return ResourceManager.GetString("StepEncashConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cif.
        /// </summary>
        public static string StepEnterCif {
            get {
                return ResourceManager.GetString("StepEnterCif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Otp.
        /// </summary>
        public static string StepEnterOtp {
            get {
                return ResourceManager.GetString("StepEnterOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin.
        /// </summary>
        public static string StepEnterPin {
            get {
                return ResourceManager.GetString("StepEnterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Fingerprints.
        /// </summary>
        public static string StepFingerprintScan {
            get {
                return ResourceManager.GetString("StepFingerprintScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Validation.
        /// </summary>
        public static string StepPinValidation {
            get {
                return ResourceManager.GetString("StepPinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string StepPrinting {
            get {
                return ResourceManager.GetString("StepPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Cash.
        /// </summary>
        public static string StepQuickCash {
            get {
                return ResourceManager.GetString("StepQuickCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Card.
        /// </summary>
        public static string StepReadCard {
            get {
                return ResourceManager.GetString("StepReadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Printing.
        /// </summary>
        public static string StepReceiptPrinting {
            get {
                return ResourceManager.GetString("StepReceiptPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email.
        /// </summary>
        public static string StepSendingEmail {
            get {
                return ResourceManager.GetString("StepSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Sms Otp.
        /// </summary>
        public static string StepSendSMSOTP {
            get {
                return ResourceManager.GetString("StepSendSMSOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Information.
        /// </summary>
        public static string StepUpdateInfo {
            get {
                return ResourceManager.GetString("StepUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Updated Successfully.
        /// </summary>
        public static string StepUpdateInfoSuccess {
            get {
                return ResourceManager.GetString("StepUpdateInfoSuccess", resourceCulture);
            }
        }
    }
}
